project:
  type: website

format:
  html:
    theme: 
      - zephyr
      - custom.scss
website:
  title: "Koichi Ito web site"
  navbar:
    pinned: false
    collapse: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "研究室"
        href: lab.qmd
#      - text: "研究内容"
#        href: research.qmd
      - text: "業績"
        href: publication.qmd
      - text: "資料"
        href: learning.qmd
    right:
      - text: "English"
        href: index_en.qmd
      - icon: envelope
        aria-label: email
        href: "mailto:koichi.ito.bio@outlook.com"  
  search: false

#for publish
# quarto publish gh-pages
