---
title: "業績"
---

[\[Koichi Ito - Google Scholar Citation\]](https://scholar.google.com/citations?hl=ja&view_op=list_works&gmla=AJsN-F6NanGQGUoTvjhhZLwxZxz03Q75J6xV7lIsD5oyKKcyCX0COH9t614j5E59fx-Q1iEfGOqTxJEFfqZ1qO3IZLDv-DyxkUGl2QKNPUr7yqrEijjoBqdH4zneP8S7xUgKKYdFGk8-15AsWAfJTXyhu91cD79Owg&user=YAl7gAYAAAAJ)

##### [Specialism and generalism in social animals in variable environments](https://doi.org/10.1098/rstb.2023.0264)
Koichi Ito, Andrew Higginson. 2025. Philosophical Transactions of the Royal Siciety B (380): 20230264.

##### [Geographic distribution of needle litter microfungi in British Columbia  ](https://doi.org/10.48550/arXiv.2304.14488)
Shunsuke Matsuoka, Koichi Ito, Takashi Osono. 2024. The Harris Science Review of Doshisha University (65-1): 8-16.

##### [Human movement avoidance decisions during Coronavirus disease 2019 in Japan](https://doi.org/10.1016/j.jtbi.2024.111795)
Ryosuke Omori, Koichi Ito, Shunsuke Kanemitsu, Ryusuke Kimura, Yoh Iwasa. 2024. Journal of Theoretical Biology (585): 111795.

##### [Time changes of customer behavior on accommodation reservation: a case study of Japan](https://doi.org/10.1007/s13160-023-00623-5)
Koichi Ito, Shunsuke Kanemitsu, Ryusuke Kimura, Ryosuke Omori. 2023. Japan Journal of Industrial and Applied Mathematics.

##### [Competition model explains trends of long‐term fertilization in plant communities](https://doi.org/10.1002/ece3.9832)
Atsushi Yamauchi, Koichi Ito, Shota Shibasaki. 2023. Ecology and Evolution (13-2): e9832.

##### [Continuous irregular dynamics with multiple neutral trajectories permit species coexistence in competitive communities](https://www.sciencedirect.com/science/article/pii/S0040580922000806)
Atsushi Yamauchi, Koichi Ito, Shota Shibasaki, Toshiyuki Namba. 2023. Theoretical Population Biology (149): 39-47. 

##### [Future behaviours decision-making regarding travel avoidance during COVID-19 outbreaks](https://www.nature.com/articles/s41598-022-24323-1)
Koichi Ito, Shunsuke Kanemitsu, Ryusuke Kimura, Ryosuke Omori. 2022. Scientific Reports(12-1): 19780. 

##### [Incorporating thermodynamics in predator–prey games predicts the diel foraging patterns of poikilothermic predators](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13608)
Koichi Ito, Andrew D. Higginson, Graeme D. Ruxton, Yannis P. Papastamatiou. 2021. Journal of Animal Ecology (00): 1-13. 

##### [Sterile males and females can synergistically suppress wild pests targeted by sterile insect technique](https://www.sciencedirect.com/science/article/pii/S0022519321002976?via%3Dihub)
Yusuke Ikegawa, Koichi Ito, Chihiro Himuro, Atsushi Honma. 2021. Journal of Theoretical Biology (530): 110878. 

##### [Colonization process determines species diversity via competitive quasi‐exclusion](https://onlinelibrary-wiley-com.ezproxy.library.ubc.ca/doi/full/10.1002/ece3.7342)
Atsushi Yamauchi, Koichi Ito, Shota Shibasaki. 2021. Ecology and Evolution (00): 1-11. 

##### [On the importance of evolving phenotype distributions on evolutionary diversification](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008733)
Gil J. B. Henriques, Koichi Ito, Christoph Hauert, Michael Doebeli. 2021. PLOS Computational Biology (17-2): e1008733 .

##### [Evolution of honest reward signal in flowers](https://royalsocietypublishing.org/doi/10.1098/rspb.2020.2848)
Koichi Ito, Miki F. Suzuki, Ko Mochizuki, 2021. Proceedings of the Royal Society B (288): 20202848.

##### [The joint evolution of cooperation and competition](https://www.sciencedirect.com/science/article/pii/S0022519319302875)
Koichi Ito, Michael Doebeli, 2019. Journal of Theoretical Biology (480): 1-12.

##### [Optimal foraging by herbivores maintains polymorphism in defence in a natural plant population](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2435.12937)
Yasuhiro Sato†, Koichi Ito†, Hiroshi Kudoh, 2017. Functional Ecology (31-12): 2233-2243.   † equal contribution

##### [The evolution of cooperation by negotiation in a noisy world](http://onlinelibrary.wiley.com/doi/10.1111/jeb.13030/abstract)
Koichi Ito, John McNamara, Atsushi Yamauchi, Andrew Higginson, 2016. Journal of Evolutionary Biology (30-3): 603-615.

##### [Relationship between aggregation of rewards and the possibility of polymorphism in continuous snowdrift games](http://www.sciencedirect.com/science/article/pii/S0022519315000740)
Koichi Ito, Hisashi Ohtsuki, Atsushi Yamauchi, 2015. Journal of Theoretical Biology (372):47-53. 

##### [Theoretical study of evolution of polymorphism in the level of anti-herbivore defense in plants](https://www.tandfonline.com/doi/full/10.1080/17429145.2010.544771)
Koichi Ito, Atsushi Yamauchi, 2011.  Journal of Plant Interactions (6):183-184.
